# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toll_info', '0008_auto_20171209_0625'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='Orders',
        ),
    ]
