# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=500)),
                ('vechile_no', models.CharField(max_length=500)),
                ('vechile_type', models.CharField(max_length=500)),
                ('users_address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_no', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(db_column='Vehicle_id', max_length=17, unique=True)),
                ('mob_no', models.CharField(blank=True, db_column='Mob_No', max_length=10, null=True, unique=True)),
                ('otp', models.CharField(blank=True, db_column='OTP', max_length=6, null=True)),
                ('token', models.CharField(db_column='Token', max_length=30)),
            ],
            options={
                'db_table': 'vehicle_details',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='users',
            name='vehicle_id',
            field=models.ForeignKey(db_column='Vehicle_id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='vin', to='login.VehicleDetails'),
        ),
    ]
