# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='vehicle_id',
            field=models.ForeignKey(db_column='vehicle_id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='vin', to='login.VehicleDetails', to_field='vehicle_id'),
        ),
    ]
