# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_delete_vehicledetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='vechile_no',
            new_name='vehicle_no',
        ),
    ]
