# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20171208_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='vehicle_id',
            field=models.CharField(blank=True, db_column='vehicle_id', max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
